### ISSUE TITLE
simple example fails

### ISSUE THREAD

**Issue by mcarifio** [ferdousbhai/deno-chat#2]
First, thank you for offering this. Unfortunately a can't make a simple example work:

```
[mcarifio@spider logpt]$p deno --version
deno 1.32.3 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3

[mcarifio@spider logpt]$p cat broken.ts
#!/usr/bin/env -S deno run --allow-all

import { askAI } from "https://deno.land/x/deno_chat@0.2.0/mod.ts";
const prompt = "what is 2 + 2?"
var answer = await askAI(prompt, { model: "text-davinci-002-render" });
console.log(answer);

[mcarifio@spider logpt]$p deno run --allow-all broken.ts 
Cannot read properties of undefined (reading '0')
```

**Comment by piero0920** [comment]
It doesn't work because `text-davinci-002-render` model is not available on the chat completion endpoint.

The only [models](https://platform.openai.com/docs/models/model-endpoint-compatibility) available are these.
- gpt-4 
- gpt-4-0314
- gpt-4-32k
- gpt-4-32k-0314
- gpt-3.5-turbo
- gpt-3.5-turbo-0301

**Comment by mcarifio** [comment]
Tried these variants to no effect. Do I have to have a paid subscription to make API calls?

**Comment by piero0920** [comment]
Yeah, you need a `.env` file with the [api key](https://github.com/ferdousbhai/deno-chat/blob/d5ebf4c4caf2f3aef7ff3466ea73cc78c9bc90e0/src/config.ts#L5).

```env
OPENAI_API_KEY="apikey"
```
The pricing is [here](https://openai.com/pricing).
